name: STM GTFS-RT fetch

on:
  schedule:
    - cron: "*/5 * * * *"   # toutes les 5 minutes
  workflow_dispatch:        # permet de lancer manuellement

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run STM fetch script
        env:
          STM_API_KEY: ${{ secrets.STM_API_KEY }}
        run: node scripts/fetch-stm.mjs

      - name: Debug after script
        run: |
          echo "CONTENU DU REPO APRÈS LE SCRIPT :"
          ls -R .

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
